# Generated by Django 6.0.4 on 2026-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('GP', 'General Practice'), ('SUR', 'Surgery'), ('PED', 'Pediatrics'), ('CAR', 'Cardiology'), ('DER', 'Dermatology')], max_length=50),
        ),
    ]
